In [1]:
import numpy as np
import time

In [2]:
#Execution Performance
size = 1_00_000

py_list = list(range(size))
start_time = time.time()
sq_list = [x ** 2 for x in py_list]
end_time = time.time()

print(f"python list time = {end_time - start_time} seconds")

np_array = np.array(py_list)
start = time.time()
sq_array = np_array ** 2
end = time.time()

print(f"numpy array time = {end - start} seconds")

python list time = 0.005915164947509766 seconds
numpy array time = 0.000728607177734375 seconds


In [3]:
#memory
import sys

print(f"python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")

print(f"numpy array size = {np_array.nbytes} bytes")

python list size = 80005600000 bytes
numpy array size = 800000 bytes


In [4]:
#create arrays from lists
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr), arr.shape)

arr2 = np.array([1, 2, 3, 4, 5, "AI/ML"])
print(arr2, type(arr2), arr2.shape)

arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(arr2D, arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' 'AI/ML'] <class 'numpy.ndarray'> (6,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)


In [5]:
#create arrays using built-in methods
arr1 = np.zeros((2, 3), dtype="int64") #prefill #with data type
print(arr1, arr1.shape)

arr3 = np.ones((5, )) #prefill
print(arr3, arr3.shape)

arr4 = np.full((3, 4), 100) #prefill with value
print(arr4, arr4.shape)

arr5 = np.eye(3) #identity matrix
print(arr5, arr5.shape)

arr6 = np.arange(1, 11, 2) #range elements
print(arr6, arr6.shape)

arr7 = np.linspace(1, 100, 4) #evenly spaced arrays
print(arr7, arr7.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1. 1. 1. 1. 1.] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[1 3 5 7 9] (5,)
[  1.  34.  67. 100.] (4,)


In [6]:
#properties
arrr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arrr.shape) #dimensions = m x n
print(arrr.size) #total elements
print(arrr.dtype) #data type
print(arrr.ndim) #dimension

float_arr = arrr.astype(np.float64)
print(float_arr, float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [7]:
#Operations on numpy arrays

#Reshaping
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr, arr.shape)

reshaped = arr.reshape((3, 2))
print(reshaped, reshaped.shape)

#flattened
flattened = arr.flatten() #2D => 1D
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [8]:
#Indexing
# arr = np.array([1, 2, 3, 4, 5])  #on 1D array
arr = np.array([[1, 2, 3], [4, 5, 6]]) #on 2D array

# print(arr[1]) #2
print(arr[1, 1]) #5
print(arr[0, 0]) #1

5
1


In [9]:
#Fancy indexing
arr = np.array([1, 2, 3, 4, 5])

idx = [0, 1, 4]
print(arr[idx])

[1 2 5]


In [10]:
#Boolean indexing
arr = np.array([1, 2, 3, 4, 5])

print(arr[arr % 2 != 0])
print(arr[arr % 2 == 0])

[1 3 5]
[2 4]


In [11]:
#slicing
arr = np.array([1, 2, 3, 4, 5])

print(arr[1:4]) #start, end, step
print(arr[1:]) #start
print(arr[:4]) #end
print(arr[::2]) #step

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 3 5]


In [12]:
#Copy vs View
nums = [1, 2, 3, 4, 5]
sub_list = nums[1:3]
print(sub_list)
sub_list[0] = 100

print(sub_list)
print(nums)

arr = np.array([1, 2, 3, 4, 5])
sub_arr = arr[1:3].copy() #copy of the view
print(sub_arr)
sub_arr[0] = 100

print(sub_arr)
print(arr)

[2, 3]
[100, 3]
[1, 2, 3, 4, 5]
[2 3]
[100   3]
[1 2 3 4 5]


In [17]:
# Mulyi-dimensional arrays
arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2D)

print(np.sum(arr2D))

sum_of_columns = np.sum(arr2D, axis = 0)
print(sum_of_columns)

sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)

#slicing on 2D array
print(arr2D[0:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]
